---
- hosts: all
  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Installer Git
      become: true
      apt:
        name: git
        state: present

    - name: Cloner un repository Git public
      git:
        repo: https://github.com/Pauline-Mdt/hitema_docker-devops_project
        dest: /home/adminuser/app

    - name: Build and run docker compose
      shell: |
        cd /home/adminuser/app
        docker-compose up > logs.txt &

    - name: Add user to docker group
      shell: |
        sudo usermod -aG docker $USER
        newgrp docker